"""add_bouquet_template_models

Revision ID: 07858e4ef3ff
Revises: 1305cdbad0e4
Create Date: 2026-04-04 16:08:26.630749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07858e4ef3ff'
down_revision: Union[str, Sequence[str], None] = '1305cdbad0e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bouquet_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('occasion', sa.String(length=50), nullable=False),
    sa.Column('color_palette', sa.String(length=50), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bouquet_templates_id'), 'bouquet_templates', ['id'], unique=False)
    op.create_table('bouquet_template_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['bouquet_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bouquet_template_items_id'), 'bouquet_template_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bouquet_template_items_id'), table_name='bouquet_template_items')
    op.drop_table('bouquet_template_items')
    op.drop_index(op.f('ix_bouquet_templates_id'), table_name='bouquet_templates')
    op.drop_table('bouquet_templates')
    # ### end Alembic commands ###
