"""add image_url to orders

Revision ID: 6bdbccff7d20
Revises: 97fe9ceaa989
Create Date: 2026-04-20 14:41:45.206515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bdbccff7d20'
down_revision: Union[str, Sequence[str], None] = '97fe9ceaa989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'image_url')
    # ### end Alembic commands ###
