"""add_composition_and_merge_softpink

Revision ID: 88f86c6e37f9
Revises: a1b2c3d4e5f6
Create Date: 2026-04-15 12:01:51.103891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88f86c6e37f9'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('products', sa.Column('composition', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # Объединяем нежно-розовый → розовый
    op.execute("UPDATE products SET flower_color = 'розовый' WHERE flower_color = 'нежно-розовый'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'composition')
    # ### end Alembic commands ###
