"""add sizes and care_tips to products

Revision ID: 97fe9ceaa989
Revises: 88f86c6e37f9
Create Date: 2026-04-17 16:50:27.750615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97fe9ceaa989'
down_revision: Union[str, Sequence[str], None] = '88f86c6e37f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sizes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('care_tips', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'care_tips')
    op.drop_column('products', 'sizes')
    # ### end Alembic commands ###
